"""
Legal Intelligence Layer — общий контур (Stage 1: схемы, clarify-first, флаг LEGAL_ENGINE).

Интеграция в хендлеры — поэтапно; без флага LEGAL_ENGINE поведение проекта не меняется.
"""

from __future__ import annotations

from app.shared.legal_engine.clarify_policy import (
    ClarifyDecision,
    clarify_for_contract_scenario,
    decide_clarify,
    should_block_generation,
)
from app.shared.legal_engine.config import legal_engine_enabled, legal_engine_telemetry_enabled
from app.shared.legal_engine.support_diagnostics import (
    diagnostics_env_snapshot,
    summarize_legal_engine_telemetry,
)
from app.shared.legal_engine.interview_policy_flow import (
    ReadyPolicyBranch,
    classify_ready_policy_branch,
    legal_engine_should_block_generation,
    merge_clarify_queue_policy_first,
    resolve_legal_engine_policy_decision,
)
from app.shared.legal_engine.intake_interpreter import (
    claims_intake_meta_patch,
    combine_claim_clarify_questions,
    enrich_claims_merged_after_extract,
    extra_clarify_questions_from_interpretation,
    interpret_claims_intake,
    interpret_consult_intake,
    merge_claims_intake_slots,
    merge_consult_interpretation,
)
from app.shared.legal_engine.schemas import (
    EvidenceRecordV1,
    IntakeInterpretation,
    LegalIntent,
    LegalRunContext,
    MoneyMention,
    MoneyModel,
    OutputContractRef,
    RetrievalPlan,
    RetrievalPlanSpec,
    ScenarioLockSource,
    StructuredFacts,
    structured_facts_from_mapping,
)
from app.shared.legal_engine.stage3 import (
    build_admin_legal_run_context,
    build_admin_rag_queries_from_context,
    build_bankruptcy_legal_run_context,
    build_bankruptcy_rag_queries_from_context,
    build_claims_legal_run_context,
    build_claims_rag_queries_from_context,
    build_consult_legal_run_context,
    build_consult_rag_queries_from_context,
    build_contract_legal_run_context,
    build_contract_rag_queries_from_context,
    build_gpo_legal_run_context,
    build_gpo_rag_queries_from_context,
    extract_money_model_for_bankruptcy,
    extract_money_model_for_claims,
    extract_money_model_for_contract,
    extract_money_model_for_gpo,
    extract_money_model_mvp,
    plan_admin_retrieval,
    plan_bankruptcy_retrieval,
    plan_claims_retrieval,
    plan_consult_retrieval,
    plan_contract_retrieval,
    plan_gpo_retrieval,
)

__all__ = [
    "ReadyPolicyBranch",
    "ClarifyDecision",
    "EvidenceRecordV1",
    "IntakeInterpretation",
    "LegalIntent",
    "LegalRunContext",
    "MoneyMention",
    "MoneyModel",
    "OutputContractRef",
    "RetrievalPlan",
    "RetrievalPlanSpec",
    "build_admin_legal_run_context",
    "build_admin_rag_queries_from_context",
    "build_bankruptcy_legal_run_context",
    "build_bankruptcy_rag_queries_from_context",
    "build_contract_legal_run_context",
    "build_contract_rag_queries_from_context",
    "build_claims_legal_run_context",
    "build_claims_rag_queries_from_context",
    "build_consult_legal_run_context",
    "build_consult_rag_queries_from_context",
    "build_gpo_legal_run_context",
    "build_gpo_rag_queries_from_context",
    "extract_money_model_for_bankruptcy",
    "extract_money_model_for_claims",
    "extract_money_model_for_contract",
    "extract_money_model_for_gpo",
    "extract_money_model_mvp",
    "enrich_claims_merged_after_extract",
    "plan_admin_retrieval",
    "plan_bankruptcy_retrieval",
    "plan_contract_retrieval",
    "plan_claims_retrieval",
    "plan_consult_retrieval",
    "plan_gpo_retrieval",
    "ScenarioLockSource",
    "StructuredFacts",
    "classify_ready_policy_branch",
    "claims_intake_meta_patch",
    "clarify_for_contract_scenario",
    "combine_claim_clarify_questions",
    "decide_clarify",
    "extra_clarify_questions_from_interpretation",
    "interpret_claims_intake",
    "interpret_consult_intake",
    "legal_engine_should_block_generation",
    "legal_engine_enabled",
    "diagnostics_env_snapshot",
    "summarize_legal_engine_telemetry",
    "merge_claims_intake_slots",
    "merge_clarify_queue_policy_first",
    "merge_consult_interpretation",
    "resolve_legal_engine_policy_decision",
    "should_block_generation",
    "structured_facts_from_mapping",
]
