# app/features/contracts/legal_nodes/manufacture_v1.py

from __future__ import annotations

from app.features.contracts.legal_nodes.supply_v1 import LegalNodeV1


MANUFACTURE_LEGAL_NODES_V1: tuple[LegalNodeV1, ...] = (
    LegalNodeV1(
        node_id="manufacture_parties_title",
        title="Стороны, преамбула, наименование договора",
        contract_section="1",
        facts_keys=("contract_title", "parties"),
        query_templates=(
            "договор стороны реквизиты полномочия представителя Республика Казахстан",
            "юридическое лицо наименование БИН адрес место заключения договора",
            "{contract_title} стороны подписант",
        ),
        default_closure_style="neutral_frame",
        risk_keys=("misidentification_party",),
        expected_sources=("kz_gk_code", "kz_law_llp_code"),
        traceability_role="Идентификация сторон по договору изготовления.",
    ),
    LegalNodeV1(
        node_id="manufacture_subject_product",
        title="Предмет: продукция, качество, соответствие ТЗ",
        contract_section="1, 2",
        facts_keys=("product", "manufacture_kind", "subject_of_contract"),
        query_templates=(
            "договор подряда предмет результат работы существенные условия",
            "подрядчик обязан сдать результат работы надлежащего качества",
            "{manufacture_kind} подряд описание результата работы заказчик",
        ),
        default_closure_style="defer_to_spec_appendix",
        risk_keys=("vague_spec",),
        expected_sources=("kz_gk_code", "kz_vs_np_invalidity_of_transactions_code"),
        traceability_role="Существенные условия предмета.",
    ),
    LegalNodeV1(
        node_id="manufacture_tz_specification",
        title="Техническое задание, спецификация, документация",
        contract_section="3",
        facts_keys=("tz", "technical_task", "specification", "product"),
        query_templates=(
            "техническое задание состав часть договора подряда приложение спецификация",
            "рабочая документация чертежи спецификация количество наименование изделий",
            "согласованное сторонами описание результата работы приложение договор подряда",
        ),
        default_closure_style="appendix_driven",
        risk_keys=("spec_gap",),
        expected_sources=("kz_gk_code",),
        traceability_role="Связь результата с ТЗ и приложениями.",
    ),
    LegalNodeV1(
        node_id="manufacture_term_transfer",
        title="Сроки изготовления, передача продукции",
        contract_section="4",
        facts_keys=("manufacture_term", "performance_terms"),
        query_templates=(
            "подрядчик обязан сдать результат работы в срок по договору подряда",
            "передача результата работы заказчику поэтапно частями договор подряда",
            "исполнение обязательства в срок должник просрочка передачи результата",
        ),
        default_closure_style="timeline_agreement",
        risk_keys=("delay_delivery",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Сроки и момент передачи.",
    ),
    LegalNodeV1(
        node_id="manufacture_price_remuneration",
        title="Цена работ, вознаграждение, НДС",
        contract_section="6, 8",
        facts_keys=(
            "manufacture_price",
            "manufacture_price_unit",
            "price",
            "price_and_payment",
            "vat_mode",
        ),
        query_templates=(
            "цена работы подряда вознаграждение подрядчика договор",
            "стоимость работ НДС налоговые обязательства подряд Казахстан",
            "изменение цены договора подряд письменное дополнительное соглашение",
        ),
        default_closure_style="written_amendment",
        risk_keys=("vat_error",),
        expected_sources=("kz_gk_code", "kz_nk_code"),
        traceability_role="Цена и налоги.",
    ),
    LegalNodeV1(
        node_id="manufacture_payment",
        title="Порядок и сроки оплаты",
        contract_section="7",
        facts_keys=("payment_terms", "payment_due", "price_and_payment"),
        query_templates=(
            "расчёты заказчика с подрядчиком аванс по договору подряда",
            "оплата принятых работ по актам выполненных работ",
            "просрочка оплаты неустойка задержка платежа заказчика",
        ),
        default_closure_style="staged_payment_general",
        risk_keys=("prepayment_exposure",),
        expected_sources=("kz_gk_code", "kz_law_currency_control_code"),
        traceability_role="Расчёты заказчика.",
    ),
    LegalNodeV1(
        node_id="manufacture_acceptance",
        title="Приёмка продукции, недостатки, претензии",
        contract_section="9",
        facts_keys=("manufacture_acceptance", "product"),
        query_templates=(
            "приёмка результата работы акт приёмки передачи подряд",
            "приёмка готовой продукции заказчиком сдача изделия по договору подряда на изготовление",
            "срок предъявления претензии заказчиком о недостатках сданной продукции со дня приёмки",
        ),
        default_closure_style="claim_window_statutory",
        risk_keys=("silent_acceptance",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Приёмка и претензионный контур.",
    ),
    LegalNodeV1(
        node_id="manufacture_quality_liability",
        title="Качество, гарантии, ответственность",
        contract_section="10, 11",
        facts_keys=(
            "quality_requirements",
            "warranty",
            "manufacture_liability",
            "liability_mode",
        ),
        query_templates=(
            "устранение недостатков работы подрядчиком безвозмездно срок",
            "гарантия на результат работы обязанности подрядчика по качеству",
            "неустойка за просрочку сдачи результата работы подряд",
        ),
        default_closure_style="capped_reasonable",
        risk_keys=("penalty_excessive",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Санкции и качество.",
    ),
    LegalNodeV1(
        node_id="manufacture_security",
        title="Обеспечение исполнения",
        contract_section="12",
        facts_keys=("manufacture_security",),
        query_templates=(
            "обеспечение исполнения обязательств задаток банковская гарантия договор",
            "возврат аванса обеспечительный платёж договор подряда",
        ),
        default_closure_style="amount_in_annex",
        risk_keys=("forfeiture_abuse",),
        expected_sources=("kz_gk_code",),
        traceability_role="Обеспечительные конструкции.",
    ),
    LegalNodeV1(
        node_id="manufacture_title_risk",
        title="Переход права, риск, материалы",
        contract_section="4",
        facts_keys=("product", "manufacture_kind"),
        query_templates=(
            "переход права собственности вещь изготовленная договор подряд отчуждение",
            "случайная гибель вещи риск до передачи вещи заказчику подряда",
            "материал предоставленный заказчиком право собственности на него отходы производства",
        ),
        default_closure_style="default_statutory",
        risk_keys=("FOT_mismatch",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Момент перехода права и рисков.",
    ),
    LegalNodeV1(
        node_id="manufacture_force_majeure",
        title="Форс-мажор",
        contract_section="13",
        facts_keys=("force_majeure",),
        query_templates=(
            "освобождение от ответственности форс мажор непреодолимая сила",
            "прекращение обязательства обстоятельства непреодолимой силы доказательство",
        ),
        default_closure_style="standard_clause",
        risk_keys=("fm_overuse",),
        expected_sources=("kz_gk_code",),
        traceability_role="Освобождение при форс-мажоре.",
    ),
    LegalNodeV1(
        node_id="manufacture_dispute_notice",
        title="Претензии, споры, уведомления",
        contract_section="16, 17",
        facts_keys=("dispute", "notice"),
        query_templates=(
            "претензионный порядок досудебный порядок урегулирования спора",
            "подсудность по месту нахождения ответчика исковая давность",
            "арбитражное соглашение третейский суд оговорка",
        ),
        default_closure_style="court_default",
        risk_keys=("jurisdiction_conflict",),
        expected_sources=(
            "kz_gk_code",
            "kz_law_arbitration_code",
            "kz_vs_np_civil_procedure_norms_code",
        ),
        traceability_role="Разрешение споров.",
    ),
    LegalNodeV1(
        node_id="manufacture_confidential_pd",
        title="Конфиденциальность, персональные данные",
        contract_section="14, 15",
        facts_keys=("confidential", "pd"),
        query_templates=(
            "конфиденциальность служебная информация коммерческая тайна договор",
            "персональные данные субъект оператор обработка Закон персональные данные",
        ),
        default_closure_style="if_applicable",
        risk_keys=("pd_overcollection",),
        expected_sources=("kz_law_personal_data_code", "kz_gk_code"),
        traceability_role="Данные и режим тайны.",
    ),
    LegalNodeV1(
        node_id="manufacture_termination",
        title="Расторжение, односторонний отказ",
        contract_section="18",
        facts_keys=("termination",),
        query_templates=(
            "расторжение договора подряда существенное нарушение условий",
            "односторонний отказ от договора заказчик подрядчик последствия",
        ),
        default_closure_style="material_breach_frame",
        risk_keys=("wrongful_termination",),
        expected_sources=("kz_gk_code", "kz_vs_np_invalidity_of_transactions_code"),
        traceability_role="Основания прекращения.",
    ),
    LegalNodeV1(
        node_id="manufacture_final_requisites",
        title="Заключительные положения, реквизиты",
        contract_section="19, 20",
        facts_keys=("notice", "parties"),
        query_templates=(
            "изменение договора письменная форма число экземпляров",
            "действие договора толкование условий приложения неотъемлемая часть",
        ),
        default_closure_style="written_form_emphasis",
        risk_keys=("oral_amendment_risk",),
        expected_sources=("kz_gk_code", "kz_law_llp_code"),
        traceability_role="Завершение договора.",
    ),
)
