# app/features/contracts/legal_nodes/rent_v1.py

from __future__ import annotations

from app.features.contracts.legal_nodes.supply_v1 import LegalNodeV1


RENT_LEGAL_NODES_V1: tuple[LegalNodeV1, ...] = (
    LegalNodeV1(
        node_id="rent_parties_title",
        title="Стороны, объект договора в шапке",
        contract_section="1",
        facts_keys=("contract_title", "parties"),
        query_templates=(
            "договор аренды Республика Казахстан арендодатель арендатор реквизиты полномочия",
            "аренда имущества существенные условия сторон договора ГК РК",
            "{contract_title} стороны преамбула договора аренды",
        ),
        default_closure_style="neutral_frame",
        risk_keys=("wrong_contract_type",),
        expected_sources=("kz_gk_code",),
        traceability_role="Вход в граф; типовые обязанности сторон аренды.",
    ),
    LegalNodeV1(
        node_id="rent_subject_description",
        title="Предмет, описание, назначение",
        contract_section="1",
        facts_keys=("rent_object", "subject_of_contract"),
        query_templates=(
            "аренда нежилое помещение договор ГК РК",
            "аренда имущества описание объекта",
            "{rent_object} аренда",
        ),
        default_closure_style="defer_technical_appendix: детали объекта в акте/приложении",
        risk_keys=("ambiguous_object",),
        expected_sources=("kz_gk_code", "kz_vs_np_invalidity_of_transactions_code"),
        traceability_role="Фиксация существенных условий аренды.",
    ),
    LegalNodeV1(
        node_id="rent_condition_handover",
        title="Состояние при передаче, перечень имущества",
        contract_section="1, 9",
        facts_keys=("rent_object", "rent_kind"),
        query_templates=(
            "передача имущества аренда акт приёма передачи ГК РК",
            "состояние объекта аренды обязанности сторон",
        ),
        default_closure_style="act_required: передача по акту; дефекты фиксируются в акте или приложении",
        risk_keys=("disputed_condition",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Доказательственная база состояния.",
    ),
    LegalNodeV1(
        node_id="rent_term",
        title="Срок аренды, пролонгация",
        contract_section="4",
        facts_keys=("rent_term", "service_term"),
        query_templates=(
            "срок аренды договор ГК РК",
            "пролонгация аренда уведомление",
            "срочный безвозмездный найм отличия",
        ),
        default_closure_style="fixed_or_indefinite_neutral: если срок не дан — «определяется соглашением сторон / приложением» без выдуманной даты",
        risk_keys=("holdover", "notice_failure"),
        expected_sources=("kz_gk_code",),
        traceability_role="Как нормы закрепили временные рамки.",
    ),
    LegalNodeV1(
        node_id="rent_rent_fee_indexation",
        title="Размер платы, индексация",
        contract_section="6",
        facts_keys=("rent_price", "service_price", "price", "price_and_payment"),
        query_templates=(
            "арендная плата размер изменение ГК РК",
            "индексация арендная плата договор",
            "аренда коммерческое помещение плата",
        ),
        default_closure_style="written_indexation_rules: индексация только по письменному механизму; без коэффициентов если нет в facts",
        risk_keys=("indexation_dispute", "vat_rent"),
        expected_sources=("kz_gk_code", "kz_nk_code"),
        traceability_role="Трасса цены и налоговых рамок.",
    ),
    LegalNodeV1(
        node_id="rent_payment_utilities",
        title="Порядок оплаты, коммуналка, доп. платежи",
        contract_section="7",
        facts_keys=("payment_terms", "price_and_payment", "intake_extras"),
        query_templates=(
            "арендная плата порядок оплаты ГК РК",
            "коммунальные услуги аренда кто платит",
            "эксплуатационные расходы аренда",
        ),
        default_closure_style="split_costs_neutral: коммуналка/эксплуатация — по соглашению или закону из RAG; без выдуманных тарифов",
        risk_keys=("utility_dispute", "triple_net_confusion"),
        expected_sources=("kz_gk_code",),
        traceability_role="Разделение платежей.",
    ),
    LegalNodeV1(
        node_id="rent_use_restrictions",
        title="Целевое использование, ограничения, субаренда",
        contract_section="2, 11",
        facts_keys=("usage_rules", "intake_extras", "rent_kind"),
        query_templates=(
            "целевое использование объекта аренды назначение помещения договор аренды ГК РК",
            "субаренда согласие арендодателя письменная форма передача части объекта",
            "ограничения пользования арендованным имуществом порядок использования объекта арендатор",
        ),
        default_closure_style="consent_based: субаренда/перепланировка — только с согласия и в письме",
        risk_keys=("unauthorized_use", "illegal_sublease"),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Контур допустимого пользования.",
    ),
    LegalNodeV1(
        node_id="rent_maintenance_repair",
        title="Текущий/капитальный ремонт",
        contract_section="11",
        facts_keys=("intake_extras", "repair"),
        query_templates=(
            "текущий ремонт аренда ГК РК",
            "капитальный ремонт арендодатель предоставление",
            "обязанность содержания имущества аренда",
        ),
        default_closure_style="gk_default_allocation: распределение по закону, уточнение ДС при коллизии",
        risk_keys=("repair_who_pays", "deterioration"),
        expected_sources=("kz_gk_code",),
        traceability_role="Сильный узел споров — обязательна трасса.",
    ),
    LegalNodeV1(
        node_id="rent_security_deposit",
        title="Обеспечительный платёж, залог аренды",
        contract_section="12",
        facts_keys=("security_deposit", "service_security"),
        query_templates=(
            "обеспечение исполнения аренда залог договор ГК РК",
            "обеспечительный платёж аренда возврат",
        ),
        default_closure_style="amount_in_annex: сумма в приложении; условия возврата из RAG",
        risk_keys=("forfeiture_abuse",),
        expected_sources=("kz_gk_code",),
        traceability_role="Влияние на обеспечительные конструкции.",
    ),
    LegalNodeV1(
        node_id="rent_liability_damage",
        title="Ответственность, ущерб, повреждения",
        contract_section="11",
        facts_keys=("rent_liability", "liability_mode"),
        query_templates=(
            "ответственность аренда повреждение имущество ГК РК",
            "возмещение убытков аренда",
            "неустойка арендная плата просрочка",
        ),
        default_closure_style="reasonable_penalty: неустойка без драконьих % если нет в facts",
        risk_keys=("damage_quantification",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Санкции и убытки.",
    ),
    LegalNodeV1(
        node_id="rent_early_termination_return",
        title="Досрочное расторжение, возврат объекта",
        contract_section="18, 9",
        facts_keys=("termination", "rent_term"),
        query_templates=(
            "расторжение договор аренды ГК РК",
            "возврат имущества аренда акт",
            "существенное нарушение аренда",
        ),
        default_closure_style="material_breach_test: без выдуманных оснований выхода; акт возврата",
        risk_keys=("wrongful_lockout", "restitution"),
        expected_sources=("kz_gk_code", "kz_vs_np_invalidity_of_transactions_code"),
        traceability_role="Связка материальности и последствий.",
    ),
    LegalNodeV1(
        node_id="rent_defects_inventory",
        title="Дефекты при приёме и возврате, претензии",
        contract_section="9",
        facts_keys=("rent_object", "supply_acceptance"),
        query_templates=(
            "претензия аренда объект недостатки ГК РК",
            "срок строительно техническая экспертиза аренда",
        ),
        default_closure_style="timeline_reasonable: сроки уведомления без фиктивных календарных дней",
        risk_keys=("deposit_withholding_dispute",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Практическая применимость.",
    ),
    LegalNodeV1(
        node_id="rent_force_majeure",
        title="Форс-мажор",
        contract_section="13",
        facts_keys=("force_majeure",),
        query_templates=("форс мажор аренда обязательства ГК РК",),
        default_closure_style="standard_clause",
        risk_keys=("fm_rent_specific",),
        expected_sources=("kz_gk_code",),
        traceability_role="",
    ),
    LegalNodeV1(
        node_id="rent_claims_dispute",
        title="Претензии, разрешение споров",
        contract_section="16, 17",
        facts_keys=("dispute", "notice"),
        query_templates=(
            "подсудность аренда договор Республика Казахстан спор по договору аренды",
            "претензионный порядок аренда досудебное урегулирование претензия арендатор арендодатель",
            "уведомления направление претензии срок рассмотрения по договору аренды",
        ),
        default_closure_style="court_default",
        risk_keys=("jurisdiction_error",),
        expected_sources=(
            "kz_gk_code",
            "kz_law_arbitration_code",
            "kz_vs_np_civil_procedure_norms_code",
        ),
        traceability_role="",
    ),
    LegalNodeV1(
        node_id="rent_confidential_pd",
        title="Конфиденциальность, ПД",
        contract_section="14, 15",
        facts_keys=("confidential", "pd"),
        query_templates=("персональные данные аренда договор ЗРК",),
        default_closure_style="if_applicable",
        risk_keys=("pd_minimization",),
        expected_sources=("kz_law_personal_data_code",),
        traceability_role="",
    ),
    LegalNodeV1(
        node_id="rent_final_misc",
        title="Уведомления, изменения, приложения",
        contract_section="16, 19",
        facts_keys=("notice", "intake_extras"),
        query_templates=(
            "изменение договора аренды письменная форма приложения неотъемлемая часть договора ГК РК",
            "уведомления сторон по договору аренды адрес направления юридически значимых сообщений",
            "действие и истечение срока договора аренды продление письменное соглашение",
        ),
        default_closure_style="written_form_emphasis",
        risk_keys=("notice_failure",),
        expected_sources=("kz_gk_code",),
        traceability_role="",
    ),
    LegalNodeV1(
        node_id="rent_requisites_signatures",
        title="Реквизиты и подписи",
        contract_section="20",
        facts_keys=("parties",),
        query_templates=(
            "реквизиты сторон договора аренды Казахстан БИН юридическое лицо",
            "подпись уполномоченного представителя договор аренды печать стороны",
        ),
        default_closure_style="placeholder_safe",
        risk_keys=("signatory_authority",),
        expected_sources=("kz_gk_code", "kz_law_llp_code"),
        traceability_role="",
    ),
)
