# app/features/contracts/legal_nodes/service_v1.py

from __future__ import annotations

from app.features.contracts.legal_nodes.supply_v1 import LegalNodeV1


SERVICE_LEGAL_NODES_V1: tuple[LegalNodeV1, ...] = (
    LegalNodeV1(
        node_id="service_parties_title",
        title="Стороны, преамбула, наименование договора",
        contract_section="1",
        facts_keys=("contract_title", "parties"),
        query_templates=(
            "договор оказания услуг Республика Казахстан стороны",
            "возмездное оказание услуг существенные условия ГК РК",
            "{contract_title} услуги",
        ),
        default_closure_style="neutral_frame",
        risk_keys=("misidentification_party",),
        expected_sources=("kz_gk_code", "kz_law_llp_code"),
        traceability_role="Идентификация сторон и типа договора об услугах.",
    ),
    LegalNodeV1(
        node_id="service_subject",
        title="Предмет и содержание услуг",
        contract_section="1, 2",
        facts_keys=("service_object", "service_kind", "subject_of_contract"),
        query_templates=(
            "предмет договора оказание услуг ГК РК",
            "объём содержание услуг договор",
            "{subject_of_contract} существенные условия возмездного оказания услуг",
        ),
        default_closure_style="defer_to_appendix: детализация в ТЗ/приложениях",
        risk_keys=("vague_subject",),
        expected_sources=("kz_gk_code", "kz_vs_np_invalidity_of_transactions_code"),
        traceability_role="Существенные условия по предмету.",
    ),
    LegalNodeV1(
        node_id="service_tz_sla",
        title="ТЗ, SLA, критерии результата",
        contract_section="3",
        facts_keys=("service_tz", "technical_task", "specification", "tz"),
        query_templates=(
            "техническое задание приложение к договору возмездного оказания услуг объём",
            "критерии результата и приёмки услуг по приложениям ГК РК",
            "уровень сервиса SLA сроки реакции договор оказания услуг",
        ),
        default_closure_style="appendix_driven",
        risk_keys=("spec_gap",),
        expected_sources=("kz_gk_code",),
        traceability_role="Связка результата с приложениями.",
    ),
    LegalNodeV1(
        node_id="service_term_schedule",
        title="Сроки и график оказания услуг",
        contract_section="4, 5",
        facts_keys=("service_term", "service_schedule", "performance_terms"),
        query_templates=(
            "срок исполнения обязательства по договору оказания услуг ГК РК",
            "график этапы оказания услуг исполнитель заказчик",
            "просрочка оказания услуг неустойка ответственность исполнителя",
        ),
        default_closure_style="timeline_agreement",
        risk_keys=("delay_cascade",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Временные рамки исполнения.",
    ),
    LegalNodeV1(
        node_id="service_price_remuneration",
        title="Цена, вознаграждение, НДС",
        contract_section="6, 8",
        facts_keys=(
            "service_price",
            "service_price_unit",
            "price",
            "price_and_payment",
            "vat_mode",
        ),
        query_templates=(
            "цена услуг договор вознаграждение ГК РК",
            "налог на добавленную стоимость услуги договор Казахстан",
            "изменение цены услуг письменная форма",
        ),
        default_closure_style="written_amendment",
        risk_keys=("vat_error", "price_surge"),
        expected_sources=("kz_gk_code", "kz_nk_code"),
        traceability_role="Ценовая и налоговая рамка.",
    ),
    LegalNodeV1(
        node_id="service_payment",
        title="Порядок и сроки оплаты",
        contract_section="7",
        facts_keys=("payment_terms", "payment_due", "price_and_payment"),
        query_templates=(
            "цена вознаграждение за услуги срок и порядок оплаты заказчик исполнитель ГК РК",
            "оплата оказанных услуг по актам счетам аванс постоплата договор",
            "неустойка пеня за просрочку оплаты вознаграждения по договору оказания услуг",
            "поэтапная оплата услуг привязка к отчётному периоду абонентская плата",
        ),
        default_closure_style="staged_payment_general",
        risk_keys=("prepayment_exposure",),
        expected_sources=("kz_gk_code", "kz_law_currency_control_code"),
        traceability_role="Режим расчётов.",
    ),
    LegalNodeV1(
        node_id="service_acceptance",
        title="Приёмка услуг, акты, претензии",
        contract_section="9",
        facts_keys=("service_acceptance",),
        query_templates=(
            "приёмка оказанных услуг акт исполнителя заказчика ГК РК",
            "акт оказанных услуг претензия срок устранение замечаний",
            "односторонний акт приёмки услуг при молчании заказчика последствия",
        ),
        default_closure_style="claim_window_statutory",
        risk_keys=("silent_acceptance",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Доказательства и сроки претензий.",
    ),
    LegalNodeV1(
        node_id="service_quality_liability",
        title="Качество, гарантии, ответственность",
        contract_section="10, 11",
        facts_keys=(
            "quality_requirements",
            "quality_guarantees",
            "warranty",
            "service_liability",
            "liability_mode",
        ),
        query_templates=(
            "недостатки результата оказания услуг устранение исполнитель безвозмездно ГК РК",
            "неустойка штраф за ненадлежащее оказание услуг исполнитель заказчик",
            "ограничение ответственности по договору оказания услуг письменная форма",
        ),
        default_closure_style="capped_reasonable",
        risk_keys=("penalty_excessive",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Санкции и качество результата.",
    ),
    LegalNodeV1(
        node_id="service_security_subcontract",
        title="Обеспечение, субисполнители",
        contract_section="12",
        facts_keys=("service_security", "subcontracting"),
        query_templates=(
            "обеспечение исполнения обязательств по договору оказания услуг задаток банковская гарантия ГК РК",
            "привлечение третьего лица субисполнителя согласие заказчика возмездное оказание услуг",
            "делегирование исполнения обязательства другому лицу согласие кредитора услуги",
        ),
        default_closure_style="consent_based_subcontract",
        risk_keys=("subcontractor_chain",),
        expected_sources=("kz_gk_code",),
        traceability_role="Обеспечение и делегирование.",
    ),
    LegalNodeV1(
        node_id="service_ip_results",
        title="Права на результаты, интеллектуальная собственность",
        contract_section="2, 15",
        facts_keys=("ip_rights",),
        query_templates=(
            "исключительные права результат услуг договор ГК РК",
            "лицензия использование результата работ услуг",
        ),
        default_closure_style="scope_in_contract",
        risk_keys=("ip_dispute",),
        expected_sources=("kz_gk_code",),
        traceability_role="Права на результаты и ИС.",
    ),
    LegalNodeV1(
        node_id="service_force_majeure",
        title="Форс-мажор",
        contract_section="13",
        facts_keys=("force_majeure",),
        query_templates=(
            "обстоятельства непреодолимой силы исполнение обязательства по договору оказания услуг должник",
            "увеличение срока исполнения вследствие непреодолимой силы убытки стороны договор услуг",
        ),
        default_closure_style="standard_clause",
        risk_keys=("fm_overuse",),
        expected_sources=("kz_gk_code",),
        traceability_role="Освобождение при форс-мажоре.",
    ),
    LegalNodeV1(
        node_id="service_dispute_notice",
        title="Претензии, споры, уведомления",
        contract_section="16, 17",
        facts_keys=("dispute", "notice"),
        query_templates=(
            "досудебный претензионный порядок урегулирования спора по договору оказания услуг ГК РК",
            "подсудность по договору оказания услуг заявление иск место ответчика Казахстан",
            "уведомление о нарушении договора срок ответа стороны претензия",
        ),
        default_closure_style="court_default",
        risk_keys=("jurisdiction_conflict",),
        expected_sources=(
            "kz_gk_code",
            "kz_law_arbitration_code",
            "kz_vs_np_civil_procedure_norms_code",
        ),
        traceability_role="Процедура разрешения споров.",
    ),
    LegalNodeV1(
        node_id="service_confidential_pd",
        title="Конфиденциальность и персональные данные",
        contract_section="14, 15",
        facts_keys=("confidential", "pd"),
        query_templates=(
            "конфиденциальность служебной информации при оказании услуг коммерческая тайна договор",
            "обработка персональных данных оператор поручение заказчика ЗРК о персональных данных",
            "режим информации с ограниченным доступом стороны договора оказания услуг",
        ),
        default_closure_style="if_applicable",
        risk_keys=("pd_overcollection",),
        expected_sources=("kz_law_personal_data_code", "kz_gk_code"),
        traceability_role="Режим данных и тайны.",
    ),
    LegalNodeV1(
        node_id="service_termination_final",
        title="Расторжение, заключительные положения",
        contract_section="18, 19",
        facts_keys=("termination", "notice"),
        query_templates=(
            "расторжение договор оказания услуг существенное нарушение ГК РК",
            "изменение договор письменная форма",
        ),
        default_closure_style="material_breach_frame",
        risk_keys=("wrongful_termination",),
        expected_sources=("kz_gk_code",),
        traceability_role="Материальность и завершение.",
    ),
    LegalNodeV1(
        node_id="service_requisites_signatures",
        title="Реквизиты и подписи",
        contract_section="20",
        facts_keys=("parties",),
        query_templates=(
            "реквизиты юридическое лицо договор Казахстан",
            "подпись уполномоченное лицо договор",
        ),
        default_closure_style="placeholder_safe",
        risk_keys=("authority_signatory",),
        expected_sources=("kz_gk_code", "kz_law_llp_code"),
        traceability_role="Завершение договора.",
    ),
)
