# app/features/contracts/legal_nodes/subcontract_v1.py

from __future__ import annotations

from app.features.contracts.legal_nodes.supply_v1 import LegalNodeV1


SUBCONTRACT_LEGAL_NODES_V1: tuple[LegalNodeV1, ...] = (
    LegalNodeV1(
        node_id="subcontract_parties_title",
        title="Стороны, преамбула, наименование договора",
        contract_section="1",
        facts_keys=("contract_title", "parties"),
        query_templates=(
            "договор подряда стороны реквизиты полномочия представителя Республика Казахстан",
            "подрядчик заказчик наименование БИН договор строительного подряда",
            "{contract_title} стороны подписант",
        ),
        default_closure_style="neutral_frame",
        risk_keys=("misidentification_party",),
        expected_sources=("kz_gk_code", "kz_law_llp_code"),
        traceability_role="Идентификация сторон по договору подряда.",
    ),
    LegalNodeV1(
        node_id="subcontract_subject_work",
        title="Предмет: виды и объём работ",
        contract_section="1, 2",
        facts_keys=("work_object", "work_kind", "subject_of_contract"),
        query_templates=(
            "договор подряда предмет объём работ существенные условия",
            "результат работы по договору подряда сдача заказчику качество",
            "{work_kind} подряд описание работ заказчик",
        ),
        default_closure_style="defer_to_spec_appendix",
        risk_keys=("vague_spec",),
        expected_sources=("kz_gk_code", "kz_vs_np_invalidity_of_transactions_code"),
        traceability_role="Существенные условия предмета работ.",
    ),
    LegalNodeV1(
        node_id="subcontract_tz_specification",
        title="ТЗ, проектная документация, сметные расчёты",
        contract_section="3",
        facts_keys=("work_tz", "tz", "technical_task", "specification", "work_object"),
        query_templates=(
            "техническое задание приложение к договору подряда проектная документация объём работ",
            "проектно-сметная документация договор строительного подряда состав работ",
            "рабочая документация чертежи согласованный сторонами состав результата работы",
        ),
        default_closure_style="appendix_driven",
        risk_keys=("spec_gap",),
        expected_sources=("kz_gk_code",),
        traceability_role="Связь объёма работ с ТЗ и приложениями.",
    ),
    LegalNodeV1(
        node_id="subcontract_term_performance",
        title="Сроки выполнения и сдачи результата работ",
        contract_section="4",
        facts_keys=("work_term", "performance_terms"),
        query_templates=(
            "подрядчик обязан сдать результат работы в срок по договору подряда",
            "исполнение работ промежуточные сроки окончание работ календарный план",
            "просрочка выполнения работ подрядчик неустойка срок сдачи",
        ),
        default_closure_style="timeline_agreement",
        risk_keys=("delay_delivery",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Сроки исполнения обязательств по работам.",
    ),
    LegalNodeV1(
        node_id="subcontract_title_risk_materials",
        title="Материалы, переход права к результату, риск",
        contract_section="4",
        facts_keys=("materials", "work_kind", "work_object"),
        query_templates=(
            "материалы для выполнения работ заказчик подрядчик право собственности",
            "переход права на результат работы после приёмки подряд отчуждение",
            "риск случайной гибели результата работы до передачи заказчику",
        ),
        default_closure_style="default_statutory",
        risk_keys=("FOT_mismatch",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Материалы, отходы, момент перехода права и рисков.",
    ),
    LegalNodeV1(
        node_id="subcontract_work_stages",
        title="Этапы работ, график (при необходимости)",
        contract_section="5",
        facts_keys=("work_stages",),
        query_templates=(
            "выполнение работ по этапам договор подряда промежуточная сдача",
            "график выполнения строительно-монтажных работ этапность",
            "поэтапная оплата привязка к этапам выполнения работ",
        ),
        default_closure_style="timeline_agreement",
        risk_keys=("delay_cascade",),
        expected_sources=("kz_gk_code",),
        traceability_role="Этапность и календарный график.",
    ),
    LegalNodeV1(
        node_id="subcontract_price_remuneration",
        title="Цена работ, вознаграждение, изменение цены, НДС",
        contract_section="6, 8",
        facts_keys=(
            "work_price",
            "work_price_unit",
            "price",
            "price_and_payment",
            "vat_mode",
        ),
        query_templates=(
            "цена работы подряда смета вознаграждение подрядчика договор",
            "НДС стоимость работ налоговые обязательства подряд Казахстан",
            "изменение цены договора подряда дополнительное соглашение объём работ",
        ),
        default_closure_style="written_amendment",
        risk_keys=("vat_error",),
        expected_sources=("kz_gk_code", "kz_nk_code"),
        traceability_role="Цена, налоги и пересмотр.",
    ),
    LegalNodeV1(
        node_id="subcontract_payment",
        title="Порядок и сроки оплаты",
        contract_section="7",
        facts_keys=("payment_terms", "payment_due", "price_and_payment"),
        query_templates=(
            "расчёты заказчика с подрядчиком аванс по договору подряда",
            "оплата выполненных работ акты КС формы первичных документов",
            "просрочка оплаты неустойка заказчик задержка платежа",
        ),
        default_closure_style="staged_payment_general",
        risk_keys=("prepayment_exposure",),
        expected_sources=("kz_gk_code", "kz_law_currency_control_code"),
        traceability_role="Денежные обязательства заказчика.",
    ),
    LegalNodeV1(
        node_id="subcontract_acceptance",
        title="Приёмка работ, дефекты, претензии",
        contract_section="9",
        facts_keys=("work_acceptance", "work_object"),
        query_templates=(
            "приёмка выполненных работ акт приёмки подряд односторонний акт",
            "срок предъявления претензий качество строительных работ",
            "скрытые недостатки результата работы гарантийный срок подряд",
        ),
        default_closure_style="claim_window_statutory",
        risk_keys=("silent_acceptance",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Приёмка и претензионный порядок.",
    ),
    LegalNodeV1(
        node_id="subcontract_quality_liability",
        title="Качество, гарантии, ответственность, субподряд, ТБ",
        contract_section="10, 11",
        facts_keys=(
            "quality_requirements",
            "warranty",
            "work_liability",
            "liability_mode",
            "safety_rules",
            "subcontracting",
        ),
        query_templates=(
            "надлежащее качество результата работы подрядчик устраняет недостатки безвозмездно срок",
            "ответственность подрядчика за действия привлечённого им субподрядчика перед заказчиком",
            "неустойка за просрочку выполнения работы подрядчик соразмерность убытки заказчика",
        ),
        default_closure_style="capped_reasonable",
        risk_keys=("penalty_excessive",),
        expected_sources=("kz_gk_code", "kz_vs_np_civil_judgment_code"),
        traceability_role="Качество, гарантия, санкции, субподряд, безопасность.",
    ),
    LegalNodeV1(
        node_id="subcontract_security",
        title="Обеспечение исполнения обязательств",
        contract_section="12",
        facts_keys=("work_security",),
        query_templates=(
            "обеспечение исполнения договора подряда задаток гарантия",
            "удержание стоимости незавершённых работ гарантийное удержание",
        ),
        default_closure_style="amount_in_annex",
        risk_keys=("forfeiture_abuse",),
        expected_sources=("kz_gk_code",),
        traceability_role="Обеспечительные меры.",
    ),
    LegalNodeV1(
        node_id="subcontract_force_majeure",
        title="Форс-мажор",
        contract_section="13",
        facts_keys=("force_majeure",),
        query_templates=(
            "обстоятельства непреодолимой силы исполнение обязательства по договору подряда должник",
            "увеличение срока исполнения вследствие непреодолимой силы убытки стороны договор подряда",
        ),
        default_closure_style="standard_clause",
        risk_keys=("fm_overuse",),
        expected_sources=("kz_gk_code",),
        traceability_role="Форс-мажор.",
    ),
    LegalNodeV1(
        node_id="subcontract_dispute_notice",
        title="Претензии, споры, уведомления",
        contract_section="16, 17",
        facts_keys=("dispute", "notice"),
        query_templates=(
            "претензионный порядок досудебный порядок урегулирования спора",
            "подсудность по месту нахождения ответчика исковая давность",
            "арбитражное соглашение третейский суд оговорка",
        ),
        default_closure_style="court_default",
        risk_keys=("jurisdiction_conflict",),
        expected_sources=(
            "kz_gk_code",
            "kz_law_arbitration_code",
            "kz_vs_np_civil_procedure_norms_code",
        ),
        traceability_role="Споры и уведомления.",
    ),
    LegalNodeV1(
        node_id="subcontract_confidential_pd",
        title="Конфиденциальность, персональные данные",
        contract_section="14, 15",
        facts_keys=("confidential", "pd"),
        query_templates=(
            "конфиденциальность коммерческая тайна договор строительного подряда",
            "персональные данные субъект оператор обработка Закон персональные данные",
        ),
        default_closure_style="if_applicable",
        risk_keys=("pd_overcollection",),
        expected_sources=("kz_law_personal_data_code", "kz_gk_code"),
        traceability_role="КД и ПД.",
    ),
    LegalNodeV1(
        node_id="subcontract_termination",
        title="Расторжение договора",
        contract_section="18",
        facts_keys=("termination",),
        query_templates=(
            "расторжение договора подряда существенное нарушение условий",
            "односторонний отказ от договора заказчик подрядчик последствия",
        ),
        default_closure_style="material_breach_frame",
        risk_keys=("wrongful_termination",),
        expected_sources=("kz_gk_code", "kz_vs_np_invalidity_of_transactions_code"),
        traceability_role="Прекращение договора.",
    ),
    LegalNodeV1(
        node_id="subcontract_final_requisites",
        title="Заключительные положения, реквизиты",
        contract_section="19, 20",
        facts_keys=("notice", "parties"),
        query_templates=(
            "изменение договора письменная форма число экземпляров",
            "действие договора толкование условий приложения неотъемлемая часть",
        ),
        default_closure_style="written_form_emphasis",
        risk_keys=("oral_amendment_risk",),
        expected_sources=("kz_gk_code", "kz_law_llp_code"),
        traceability_role="Заключительные положения и реквизиты.",
    ),
)
